# Generated by Django 5.1.7 on 2025-03-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_trackingdata_speed_alter_trackingdata_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdata',
            name='over_speeding',
            field=models.BooleanField(default=False),
        ),
    ]
