# Generated by Django 5.1.7 on 2025-03-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_trackingdata_over_speeding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingdata',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='speed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
